# Generated by Django 4.2.21 on 2025-06-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "social_protection",
            "0015_historicallocationbenefitplanpaymentpoint_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="status",
            field=models.CharField(
                choices=[
                    ("POTENTIAL", "POTENTIAL"),
                    ("VALIDATED", "VALIDATED"),
                    ("ACTIVE", "ACTIVE"),
                    ("GRADUATED", "GRADUATED"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="groupbeneficiary",
            name="status",
            field=models.CharField(
                choices=[
                    ("POTENTIAL", "POTENTIAL"),
                    ("VALIDATED", "VALIDATED"),
                    ("ACTIVE", "ACTIVE"),
                    ("GRADUATED", "GRADUATED"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbeneficiary",
            name="status",
            field=models.CharField(
                choices=[
                    ("POTENTIAL", "POTENTIAL"),
                    ("VALIDATED", "VALIDATED"),
                    ("ACTIVE", "ACTIVE"),
                    ("GRADUATED", "GRADUATED"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgroupbeneficiary",
            name="status",
            field=models.CharField(
                choices=[
                    ("POTENTIAL", "POTENTIAL"),
                    ("VALIDATED", "VALIDATED"),
                    ("ACTIVE", "ACTIVE"),
                    ("GRADUATED", "GRADUATED"),
                    ("SUSPENDED", "SUSPENDED"),
                ],
                max_length=100,
            ),
        ),
    ]
